spring.application.name=zapateria-back
server.port=8081

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/zapateria
spring.datasource.username=reibin
spring.datasource.password=reibin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# JWT Configuration
jwt.secret=YXBwLWJhc2U2NC1zZWNyZXQtZm9yLXphcGF0ZXJpYS0yMDI2LXNlcnZlcg==
jwt.expiration-ms=86400000
